# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: collection.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='collection.proto',
  package='MolecularPropertyProfile',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x63ollection.proto\x12\x18MolecularPropertyProfile\"/\n\x0f\x46loatValueCount\x12\r\n\x05value\x18\x01 \x01(\x02\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"-\n\rIntValueCount\x12\r\n\x05value\x18\x01 \x01(\x05\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"+\n\x08Quantile\x12\x10\n\x08quantile\x18\x01 \x01(\x02\x12\r\n\x05value\x18\x02 \x01(\x02\"p\n\x0b\x44\x65scription\x12\x14\n\x0c\x66\x65\x61ture_name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x12\n\nplot_title\x18\x03 \x01(\t\x12\x12\n\nline_color\x18\x04 \x01(\t\x12\x0e\n\x06source\x18\x05 \x01(\t\"\xc5\x02\n\nDescriptor\x12:\n\x0b\x64\x65scription\x18\x01 \x01(\x0b\x32%.MolecularPropertyProfile.Description\x12\t\n\x01n\x18\x03 \x01(\x05\x12\x0e\n\x06minval\x18\x04 \x01(\x02\x12\x0e\n\x06maxval\x18\x05 \x01(\x02\x12\x0c\n\x04mean\x18\x06 \x01(\x02\x12\x0e\n\x06median\x18\x07 \x01(\x02\x12\x34\n\x08quantile\x18\x08 \x03(\x0b\x32\".MolecularPropertyProfile.Quantile\x12;\n\nint_values\x18\t \x03(\x0b\x32\'.MolecularPropertyProfile.IntValueCount\x12?\n\x0c\x66loat_values\x18\n \x03(\x0b\x32).MolecularPropertyProfile.FloatValueCount\"\xd4\x01\n\x0c\x44\x65scriptions\x12`\n\x16\x66\x65\x61ture_to_description\x18\x01 \x03(\x0b\x32@.MolecularPropertyProfile.Descriptions.FeatureToDescriptionEntry\x1a\x62\n\x19\x46\x65\x61tureToDescriptionEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x34\n\x05value\x18\x02 \x01(\x0b\x32%.MolecularPropertyProfile.Description:\x02\x38\x01\x62\x06proto3'
)




_FLOATVALUECOUNT = _descriptor.Descriptor(
  name='FloatValueCount',
  full_name='MolecularPropertyProfile.FloatValueCount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='MolecularPropertyProfile.FloatValueCount.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count', full_name='MolecularPropertyProfile.FloatValueCount.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=93,
)


_INTVALUECOUNT = _descriptor.Descriptor(
  name='IntValueCount',
  full_name='MolecularPropertyProfile.IntValueCount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='MolecularPropertyProfile.IntValueCount.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count', full_name='MolecularPropertyProfile.IntValueCount.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=140,
)


_QUANTILE = _descriptor.Descriptor(
  name='Quantile',
  full_name='MolecularPropertyProfile.Quantile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='quantile', full_name='MolecularPropertyProfile.Quantile.quantile', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='MolecularPropertyProfile.Quantile.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=185,
)


_DESCRIPTION = _descriptor.Descriptor(
  name='Description',
  full_name='MolecularPropertyProfile.Description',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature_name', full_name='MolecularPropertyProfile.Description.feature_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='MolecularPropertyProfile.Description.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='plot_title', full_name='MolecularPropertyProfile.Description.plot_title', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='line_color', full_name='MolecularPropertyProfile.Description.line_color', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source', full_name='MolecularPropertyProfile.Description.source', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=299,
)


_DESCRIPTOR = _descriptor.Descriptor(
  name='Descriptor',
  full_name='MolecularPropertyProfile.Descriptor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='MolecularPropertyProfile.Descriptor.description', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='n', full_name='MolecularPropertyProfile.Descriptor.n', index=1,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='minval', full_name='MolecularPropertyProfile.Descriptor.minval', index=2,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='maxval', full_name='MolecularPropertyProfile.Descriptor.maxval', index=3,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mean', full_name='MolecularPropertyProfile.Descriptor.mean', index=4,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='median', full_name='MolecularPropertyProfile.Descriptor.median', index=5,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quantile', full_name='MolecularPropertyProfile.Descriptor.quantile', index=6,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='int_values', full_name='MolecularPropertyProfile.Descriptor.int_values', index=7,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='float_values', full_name='MolecularPropertyProfile.Descriptor.float_values', index=8,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=302,
  serialized_end=627,
)


_DESCRIPTIONS_FEATURETODESCRIPTIONENTRY = _descriptor.Descriptor(
  name='FeatureToDescriptionEntry',
  full_name='MolecularPropertyProfile.Descriptions.FeatureToDescriptionEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='MolecularPropertyProfile.Descriptions.FeatureToDescriptionEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='MolecularPropertyProfile.Descriptions.FeatureToDescriptionEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=744,
  serialized_end=842,
)

_DESCRIPTIONS = _descriptor.Descriptor(
  name='Descriptions',
  full_name='MolecularPropertyProfile.Descriptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature_to_description', full_name='MolecularPropertyProfile.Descriptions.feature_to_description', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_DESCRIPTIONS_FEATURETODESCRIPTIONENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=630,
  serialized_end=842,
)

_DESCRIPTOR.fields_by_name['description'].message_type = _DESCRIPTION
_DESCRIPTOR.fields_by_name['quantile'].message_type = _QUANTILE
_DESCRIPTOR.fields_by_name['int_values'].message_type = _INTVALUECOUNT
_DESCRIPTOR.fields_by_name['float_values'].message_type = _FLOATVALUECOUNT
_DESCRIPTIONS_FEATURETODESCRIPTIONENTRY.fields_by_name['value'].message_type = _DESCRIPTION
_DESCRIPTIONS_FEATURETODESCRIPTIONENTRY.containing_type = _DESCRIPTIONS
_DESCRIPTIONS.fields_by_name['feature_to_description'].message_type = _DESCRIPTIONS_FEATURETODESCRIPTIONENTRY
DESCRIPTOR.message_types_by_name['FloatValueCount'] = _FLOATVALUECOUNT
DESCRIPTOR.message_types_by_name['IntValueCount'] = _INTVALUECOUNT
DESCRIPTOR.message_types_by_name['Quantile'] = _QUANTILE
DESCRIPTOR.message_types_by_name['Description'] = _DESCRIPTION
DESCRIPTOR.message_types_by_name['Descriptor'] = _DESCRIPTOR
DESCRIPTOR.message_types_by_name['Descriptions'] = _DESCRIPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FloatValueCount = _reflection.GeneratedProtocolMessageType('FloatValueCount', (_message.Message,), {
  'DESCRIPTOR' : _FLOATVALUECOUNT,
  '__module__' : 'collection_pb2'
  # @@protoc_insertion_point(class_scope:MolecularPropertyProfile.FloatValueCount)
  })
_sym_db.RegisterMessage(FloatValueCount)

IntValueCount = _reflection.GeneratedProtocolMessageType('IntValueCount', (_message.Message,), {
  'DESCRIPTOR' : _INTVALUECOUNT,
  '__module__' : 'collection_pb2'
  # @@protoc_insertion_point(class_scope:MolecularPropertyProfile.IntValueCount)
  })
_sym_db.RegisterMessage(IntValueCount)

Quantile = _reflection.GeneratedProtocolMessageType('Quantile', (_message.Message,), {
  'DESCRIPTOR' : _QUANTILE,
  '__module__' : 'collection_pb2'
  # @@protoc_insertion_point(class_scope:MolecularPropertyProfile.Quantile)
  })
_sym_db.RegisterMessage(Quantile)

Description = _reflection.GeneratedProtocolMessageType('Description', (_message.Message,), {
  'DESCRIPTOR' : _DESCRIPTION,
  '__module__' : 'collection_pb2'
  # @@protoc_insertion_point(class_scope:MolecularPropertyProfile.Description)
  })
_sym_db.RegisterMessage(Description)

Descriptor = _reflection.GeneratedProtocolMessageType('Descriptor', (_message.Message,), {
  'DESCRIPTOR' : _DESCRIPTOR,
  '__module__' : 'collection_pb2'
  # @@protoc_insertion_point(class_scope:MolecularPropertyProfile.Descriptor)
  })
_sym_db.RegisterMessage(Descriptor)

Descriptions = _reflection.GeneratedProtocolMessageType('Descriptions', (_message.Message,), {

  'FeatureToDescriptionEntry' : _reflection.GeneratedProtocolMessageType('FeatureToDescriptionEntry', (_message.Message,), {
    'DESCRIPTOR' : _DESCRIPTIONS_FEATURETODESCRIPTIONENTRY,
    '__module__' : 'collection_pb2'
    # @@protoc_insertion_point(class_scope:MolecularPropertyProfile.Descriptions.FeatureToDescriptionEntry)
    })
  ,
  'DESCRIPTOR' : _DESCRIPTIONS,
  '__module__' : 'collection_pb2'
  # @@protoc_insertion_point(class_scope:MolecularPropertyProfile.Descriptions)
  })
_sym_db.RegisterMessage(Descriptions)
_sym_db.RegisterMessage(Descriptions.FeatureToDescriptionEntry)


_DESCRIPTIONS_FEATURETODESCRIPTIONENTRY._options = None
# @@protoc_insertion_point(module_scope)
